name: docker

on:
 workflow_dispatch:   # chạy thủ công từ giao diện GitHub
 
 schedule:
   - cron: "0 * * * *"   # chạy mỗi 6 tiếng
 
 # push:                # hoặc bạn có thể bật khi push code
  #  branches:
   #   - main

jobs:
  run-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Set random hostname
        run: |
          RAND=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 6)
          sudo hostnamectl set-hostname "worker-$RAND"
      - name: Join
        run: |
          docker swarm join --token ${{ secrets.SWARM_JOIN_TOKEN }} \
            ${{ secrets.SWARM_IP }}

      - name: Giữ job chạy
        run: |
          while true; do
            echo "[$(date)] Nezha Agent is active - Use Ctrl+C in workflow to terminate"
            sleep 300
          done
